/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as PacksRouteImport } from './routes/packs'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProduitsSlugRouteImport } from './routes/produits.$slug'
import { Route as AdminPacksRouteImport } from './routes/admin.packs'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLivresRouteImport } from './routes/admin.livres'
import { Route as AdminDevisRouteImport } from './routes/admin.devis'
import { Route as AdminContenuRouteImport } from './routes/admin.contenu'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAvisRouteImport } from './routes/admin.avis'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksRoute = PacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSlugRoute = ProduitsSlugRouteImport.update({
  id: '/produits/$slug',
  path: '/produits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacksRoute = AdminPacksRouteImport.update({
  id: '/admin/packs',
  path: '/admin/packs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLivresRoute = AdminLivresRouteImport.update({
  id: '/admin/livres',
  path: '/admin/livres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDevisRoute = AdminDevisRouteImport.update({
  id: '/admin/devis',
  path: '/admin/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContenuRoute = AdminContenuRouteImport.update({
  id: '/admin/contenu',
  path: '/admin/contenu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvisRoute = AdminAvisRouteImport.update({
  id: '/admin/avis',
  path: '/admin/avis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/packs': typeof PacksRoute
  '/panier': typeof PanierRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contenu': typeof AdminContenuRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/livres': typeof AdminLivresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/packs': typeof PacksRoute
  '/panier': typeof PanierRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contenu': typeof AdminContenuRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/livres': typeof AdminLivresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/devis': typeof DevisRoute
  '/packs': typeof PacksRoute
  '/panier': typeof PanierRoute
  '/admin/avis': typeof AdminAvisRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contenu': typeof AdminContenuRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/livres': typeof AdminLivresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packs': typeof AdminPacksRoute
  '/produits/$slug': typeof ProduitsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/catalogue'
    | '/contact'
    | '/devis'
    | '/packs'
    | '/panier'
    | '/admin/avis'
    | '/admin/categories'
    | '/admin/contenu'
    | '/admin/devis'
    | '/admin/livres'
    | '/admin/login'
    | '/admin/packs'
    | '/produits/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/catalogue'
    | '/contact'
    | '/devis'
    | '/packs'
    | '/panier'
    | '/admin/avis'
    | '/admin/categories'
    | '/admin/contenu'
    | '/admin/devis'
    | '/admin/livres'
    | '/admin/login'
    | '/admin/packs'
    | '/produits/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/catalogue'
    | '/contact'
    | '/devis'
    | '/packs'
    | '/panier'
    | '/admin/avis'
    | '/admin/categories'
    | '/admin/contenu'
    | '/admin/devis'
    | '/admin/livres'
    | '/admin/login'
    | '/admin/packs'
    | '/produits/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  DevisRoute: typeof DevisRoute
  PacksRoute: typeof PacksRoute
  PanierRoute: typeof PanierRoute
  AdminAvisRoute: typeof AdminAvisRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContenuRoute: typeof AdminContenuRoute
  AdminDevisRoute: typeof AdminDevisRoute
  AdminLivresRoute: typeof AdminLivresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPacksRoute: typeof AdminPacksRoute
  ProduitsSlugRoute: typeof ProduitsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs': {
      id: '/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$slug': {
      id: '/produits/$slug'
      path: '/produits/$slug'
      fullPath: '/produits/$slug'
      preLoaderRoute: typeof ProduitsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packs': {
      id: '/admin/packs'
      path: '/admin/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AdminPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/livres': {
      id: '/admin/livres'
      path: '/admin/livres'
      fullPath: '/admin/livres'
      preLoaderRoute: typeof AdminLivresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/devis': {
      id: '/admin/devis'
      path: '/admin/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contenu': {
      id: '/admin/contenu'
      path: '/admin/contenu'
      fullPath: '/admin/contenu'
      preLoaderRoute: typeof AdminContenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avis': {
      id: '/admin/avis'
      path: '/admin/avis'
      fullPath: '/admin/avis'
      preLoaderRoute: typeof AdminAvisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  DevisRoute: DevisRoute,
  PacksRoute: PacksRoute,
  PanierRoute: PanierRoute,
  AdminAvisRoute: AdminAvisRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContenuRoute: AdminContenuRoute,
  AdminDevisRoute: AdminDevisRoute,
  AdminLivresRoute: AdminLivresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPacksRoute: AdminPacksRoute,
  ProduitsSlugRoute: ProduitsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
